language: python
python:
  - "2.7"
  - "3.3"
install:
  # Install conda
  - sudo pip install conda
  # install deps
  - sudo conda init
  - sudo conda update conda --yes
  - deps='pip numpy nose sphinx'
  - conda create --yes -n testenv python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install --yes $deps
  - pip install -e .
  # install your own package into the environment
  - python setup.py install
script:
  - "nosetests -v --with-doctest"
